name: .NET Core Desktop

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
env:
      Solution_Name: SpotKick.sln             
      Project_Directory: SpotKick.Desktop
      Project_Path: SpotKick.Desktop/SpotKick.Desktop.csproj      

jobs:

  deploy:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: setup
      uses: actions/setup-dotnet@v1

    - name: Restore the application
      run: dotnet restore ${{env.Project_Path}}

    - name: Create the app package
      run: dotnet build ${{ env.Project_Path}} -c Release --no-restore

    - name: Publish 
      run: dotnet publish ${{env.Project_Path}} -c Release --self-contained -r win-x64 -p:PublishSingleFile=true